version: "3.9"
services:   

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-mongo-livraria:/data/db

    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      
volumes:
  db-mongo-livraria: